// SPDX-License-Identifier: Apache-2.0
// Writes src/icons.tsx: the MingCute icons we use, as plain React components. Run `bun run icons` after changing
// the list below. A value starting with "<" is our own path, drawn in MingCute's style where it has no fit.
import { icons } from "@iconify-json/mingcute";

const used: Record<string, string> = {
	Archive: "archive-line",
	Bold: "bold-line",
	CalendarDays: "calendar-line",
	Check: "check-line",
	ChevronLeft: "left-line",
	ChevronRight: "right-line",
	// MingCute's selector-vertical is only 4px wide.
	ChevronsUpDown:
		'<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" d="m8 15l4 4l4-4M8 9l4-4l4 4"/>',
	Clock: "time-line",
	Copy: "copy-2-line",
	File: "file-line",
	FileArchive: "file-zip-line",
	FileAudio: "file-music-line",
	FileImage: "pic-line",
	FileSpreadsheet: "table-line",
	FileText: "document-line",
	FileVideo: "video-line",
	Folder: "folder-line",
	Forward: "corner-up-right-line",
	Inbox: "inbox-line",
	Italic: "italic-line",
	Layers: "layers-line",
	Mail: "mail-line",
	MailOpen: "mail-open-line",
	Paperclip: "attachment-line",
	PenLine: "pen-line",
	Plus: "add-line",
	Reply: "corner-up-left-line",
	Search: "search-line",
	Send: "send-plane-line",
	ShieldAlert: "forbid-circle-line",
	Star: "star-line",
	Trash2: "delete-2-line",
	Underline: "underline-line",
	User: "user-3-line",
	X: "close-line",
};

// SVG markup to JSX; the stroke width moves to the <svg> so a `strokeWidth` prop reaches every path.
const jsx = (body: string) =>
	body
		.replace(/\s?stroke-width="[^"]*"/g, "")
		.replace(/([a-z]+)-([a-z]+)=/g, (_, a: string, b: string) => `${a}${b[0]?.toUpperCase()}${b.slice(1)}=`);

const lines = Object.entries(used).map(([name, id]) => {
	const body = id.startsWith("<") ? id : icons.icons[id]?.body;
	if (!body) throw new Error(`MingCute has no ${id}`);
	return `export const ${name} = icon(<>${jsx(body)}</>);`;
});

await Bun.write(
	new URL("../src/icons.tsx", import.meta.url),
	`// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/icons.ts from MingCute (Apache-2.0, https://github.com/Richard9394/MingCute). Don't edit.
import type { ReactNode, SVGProps } from "react";

export type IconProps = SVGProps<SVGSVGElement>;

const icon =
	(paths: ReactNode) =>
	({ strokeWidth = 2, ...props }: IconProps) => (
		<svg
			xmlns="http://www.w3.org/2000/svg"
			width={24}
			height={24}
			viewBox="0 0 24 24"
			strokeWidth={strokeWidth}
			aria-hidden
			{...props}
		>
			{paths}
		</svg>
	);

${lines.join("\n")}
`,
);
