// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/icons.ts from MingCute (Apache-2.0, https://github.com/Richard9394/MingCute). Don't edit.
import type { ReactNode, SVGProps } from "react";

export type IconProps = SVGProps<SVGSVGElement>;

const icon =
	(paths: ReactNode) =>
	({ strokeWidth = 2, ...props }: IconProps) => (
		<svg
			xmlns="http://www.w3.org/2000/svg"
			width={24}
			height={24}
			viewBox="0 0 24 24"
			strokeWidth={strokeWidth}
			aria-hidden
			{...props}
		>
			{paths}
		</svg>
	);

export const Archive = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			strokeLinejoin="round"
			d="M4 8h16m-8 3v5m-2.121-1.521L12 16.6l2.121-2.121m5.586-7.772l-2.414-2.414A1 1 0 0 0 16.586 4H7.414a1 1 0 0 0-.707.293L4.293 6.707A1 1 0 0 0 4 7.414V19a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V7.414a1 1 0 0 0-.293-.707"
		/>
	</>,
);
export const Bold = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinejoin="round"
			d="M6 12h7a4 4 0 0 0 0-8H6zm0 0h8a4 4 0 0 1 0 8H6z"
		/>
	</>,
);
export const CalendarDays = icon(
	<>
		<path
			fill="currentColor"
			d="M17 4a1 1 0 1 0-2 0zm-2 2a1 1 0 1 0 2 0zM9 4a1 1 0 0 0-2 0zM7 6a1 1 0 0 0 2 0zM5 6v1h14V5H5zm15 1h-1v12h2V7zm-1 13v-1H5v2h14zM4 19h1V7H3v12zm0-8v1h16v-2H4zm12-7h-1v2h2V4zM8 4H7v2h2V4zM5 20v-1H3a2 2 0 0 0 2 2zm15-1h-1v2a2 2 0 0 0 2-2zM19 6v1h2a2 2 0 0 0-2-2zM5 6V5a2 2 0 0 0-2 2h2z"
		/>
	</>,
);
export const Check = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			strokeLinejoin="round"
			d="m3.514 11.83l5.657 5.656L20.485 6.172"
		/>
	</>,
);
export const ChevronLeft = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			strokeLinejoin="round"
			d="M14.657 17.657L9 12l5.657-5.657"
		/>
	</>,
);
export const ChevronRight = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			strokeLinejoin="round"
			d="M9.343 6.343L15 12l-5.657 5.657"
		/>
	</>,
);
export const ChevronsUpDown = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			strokeLinejoin="round"
			d="m8 15l4 4l4-4M8 9l4-4l4 4"
		/>
	</>,
);
export const Clock = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			strokeLinejoin="round"
			d="M12 7v5l3 3m6-3a9 9 0 1 1-18 0a9 9 0 0 1 18 0"
		/>
	</>,
);
export const Copy = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			d="M8 6V4a1 1 0 0 1 1-1h11a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1h-2M4 21h11a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1Z"
		/>
	</>,
);
export const File = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			d="M13 3v5.5a.5.5 0 0 0 .5.5H19m-5.414-6H6a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8.414a1 1 0 0 0-.293-.707l-4.414-4.414A1 1 0 0 0 13.586 3Z"
		/>
	</>,
);
export const FileArchive = icon(
	<>
		<path
			fill="currentColor"
			d="M10 13a1 1 0 1 0 0 2zm1 2a1 1 0 1 0 0-2zm-1-6a1 1 0 0 0 0 2zm1 2a1 1 0 1 0 0-2zm2 0a1 1 0 1 0 0 2zm1 2a1 1 0 1 0 0-2zm-1-6a1 1 0 1 0 0 2zm1 2a1 1 0 1 0 0-2zm.293-5.707L13.586 4zM19 8.414h-1V20h2V8.414zM18 21v-1H6v2h12zM5 20h1V4H4v16zM6 3v1h7.586V2H6zm8.293.293L13.586 4L18 8.414l.707-.707l.707-.707L15 2.586zM10 21h1v-3.5H9V21zm.5-4v1h3v-2h-3zm3.5.5h-1V21h2v-3.5zM10 14v1h1v-2h-1zm0-4v1h1V9h-1zm3 2v1h1v-2h-1zm0-4v1h1V7h-1zm.5 9v1a.5.5 0 0 1-.5-.5h2a1.5 1.5 0 0 0-1.5-1.5zm-3.5.5h1a.5.5 0 0 1-.5.5v-2A1.5 1.5 0 0 0 9 17.5zM13.586 3v1l.707-.707l.707-.707A2 2 0 0 0 13.586 2zM6 21v-1H4a2 2 0 0 0 2 2zm13-1h-1v2a2 2 0 0 0 2-2zm0-11.586h1A2 2 0 0 0 19.414 7l-.707.707l-.707.707zM5 4h1V2a2 2 0 0 0-2 2z"
		/>
	</>,
);
export const FileAudio = icon(
	<>
		<path fill="currentColor" d="M12 16a1 1 0 1 1-2 0a1 1 0 0 1 2 0" />
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			d="M13 3v5.5a.5.5 0 0 0 .5.5H19m-7 7v-3.14a.5.5 0 0 1 .342-.474L13.5 12M12 16a1 1 0 1 1-2 0a1 1 0 0 1 2 0Zm1.586-13H6a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8.414a1 1 0 0 0-.293-.707l-4.414-4.414A1 1 0 0 0 13.586 3Z"
		/>
	</>,
);
export const FileImage = icon(
	<>
		<path fill="currentColor" d="M16 8.5a.5.5 0 1 1-1 0a.5.5 0 0 1 1 0" />
		<path
			fill="currentColor"
			d="M14.121 14.879a1 1 0 1 0 1.415 1.414l-.708-.707zm2.829-1.415l.707-.707a1 1 0 0 0-1.414 0zm3.328 4.743a1 1 0 0 0 1.414-1.414l-.707.707zm-10.4-7.571l.708-.707a1 1 0 0 0-1.415 0zm5.158 6.571a1 1 0 0 0 1.414-1.414l-.707.707zM4 4v1h16V3H4zm17 1h-1v14h2V5zm-1 15v-1H4v2h16zM3 19h1V5H2v14zm11.828-3.414l.708.707l2.12-2.121l-.706-.708l-.707-.707l-2.122 2.122zm2.122-2.122l-.707.707l4.035 4.036l.707-.707l.707-.707l-4.035-4.036zm-7.071-2.828l-.707.707l5.864 5.864l.707-.707l.707-.707l-5.864-5.864zM3 17.515l.707.707l6.879-6.879l-.707-.707l-.707-.707l-6.88 6.879zM16 8.5h-1a.5.5 0 0 1 .5-.5v2A1.5 1.5 0 0 0 17 8.5zm-.5.5V8a.5.5 0 0 1 .5.5h-2a1.5 1.5 0 0 0 1.5 1.5zm-.5-.5h1a.5.5 0 0 1-.5.5V7A1.5 1.5 0 0 0 14 8.5zm.5-.5v1a.5.5 0 0 1-.5-.5h2A1.5 1.5 0 0 0 15.5 7zM4 20v-1H2a2 2 0 0 0 2 2zm17-1h-1v2a2 2 0 0 0 2-2zM20 4v1h2a2 2 0 0 0-2-2zM4 4V3a2 2 0 0 0-2 2h2z"
		/>
	</>,
);
export const FileSpreadsheet = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			d="M4 9h16M4 14h16M12 4v16m-7 0h14a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1Z"
		/>
	</>,
);
export const FileText = icon(
	<>
		<g fill="none" fillRule="evenodd">
			<path d="m12.593 23.258l-.011.002l-.071.035l-.02.004l-.014-.004l-.071-.035q-.016-.005-.024.005l-.004.01l-.017.428l.005.02l.01.013l.104.074l.015.004l.012-.004l.104-.074l.012-.016l.004-.017l-.017-.427q-.004-.016-.017-.018m.265-.113l-.013.002l-.185.093l-.01.01l-.003.011l.018.43l.005.012l.008.007l.201.093q.019.005.029-.008l.004-.014l-.034-.614q-.005-.018-.02-.022m-.715.002a.02.02 0 0 0-.027.006l-.006.014l-.034.614q.001.018.017.024l.015-.002l.201-.093l.01-.008l.004-.011l.017-.43l-.003-.012l-.01-.01z" />
			<path
				fill="currentColor"
				d="M4 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zm14 0H6v16h12zM8 9a1 1 0 0 1 1-1h6a1 1 0 1 1 0 2H9a1 1 0 0 1-1-1m1 4a1 1 0 1 0 0 2h3a1 1 0 1 0 0-2z"
			/>
		</g>
	</>,
);
export const FileVideo = icon(
	<>
		<path fill="none" stroke="currentColor" d="M3 5a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z" />
		<path
			fill="none"
			stroke="currentColor"
			d="M9.946 8.557a.235.235 0 0 0-.328.19c-.06.515-.169 1.643-.169 3.147s.108 2.633.17 3.147c.018.159.18.253.326.19c.472-.203 1.49-.668 2.81-1.43a27 27 0 0 0 2.643-1.718a.234.234 0 0 0 0-.378a27 27 0 0 0-2.642-1.721a27 27 0 0 0-2.81-1.427Z"
		/>
	</>,
);
export const Folder = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			d="M3 5a1 1 0 0 1 1-1h5.52a1 1 0 0 1 .78.375l1.4 1.75a1 1 0 0 0 .78.375H20a1 1 0 0 1 1 1V19a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"
		/>
	</>,
);
export const Forward = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			strokeLinejoin="round"
			d="M14.5 13.5L19 9l-4.5-4.5m4 4.5H8a2 2 0 0 0-2 2v7"
		/>
	</>,
);
export const Inbox = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			d="M3.5 12h5a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 .5.5h5a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 .5-.5h5m.236-.461l-3.448-6.035A1 1 0 0 0 16.42 5H7.58a1 1 0 0 0-.868.504l-3.448 6.035A2 2 0 0 0 3 12.53V18a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-5.469a2 2 0 0 0-.264-.992Z"
		/>
	</>,
);
export const Italic = icon(
	<>
		<path fill="none" stroke="currentColor" strokeLinecap="round" d="M10 4h6m-3 0l-2 16m-3 0h6" />
	</>,
);
export const Layers = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			d="M7 14.4v1.77a1.5 1.5 0 0 0 1.794 1.471L10 17.4m-3-3V9.64a2 2 0 0 1 1.608-1.962l6.598-1.32A1.5 1.5 0 0 1 17 7.83V9.6M7 14.4l-1.206.241A1.5 1.5 0 0 1 4 13.171V6.64a2 2 0 0 1 1.608-1.962l6.598-1.32A1.5 1.5 0 0 1 14 4.83V6.5m3 3.1l-5.392 1.078A2 2 0 0 0 10 12.64v4.76m7-7.8l1.206-.241A1.5 1.5 0 0 1 20 10.829v6.531a2 2 0 0 1-1.608 1.962l-6.598 1.32A1.5 1.5 0 0 1 10 19.17V17.4"
		/>
	</>,
);
export const Mail = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			d="m3 6.5l8.68 7.233a.5.5 0 0 0 .64 0L21 6.5M4 19h16a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1Z"
		/>
	</>,
);
export const MailOpen = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			d="m3 9.01l8.723 5.805a.5.5 0 0 0 .554 0L21 9.01m-9.555-5.64l-8 5.333A1 1 0 0 0 3 9.535V19a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V9.535a1 1 0 0 0-.445-.832l-8-5.333a1 1 0 0 0-1.11 0Z"
		/>
	</>,
);
export const Paperclip = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			d="m12.877 4.308l6.54 6.54a5.25 5.25 0 0 1-7.424 7.425l-7.954-7.954a3.501 3.501 0 1 1 4.952-4.952l7.953 7.953a1.751 1.751 0 1 1-2.477 2.477L7.22 8.55"
		/>
	</>,
);
export const PenLine = icon(
	<>
		<path
			fill="currentColor"
			d="m3.929 20.071l-.964-.268a1 1 0 0 0 1.232 1.232zm6.364-1.414l.12.993zm-4.95-4.95l.993.12zm14.143-4.95A1 1 0 1 0 20.9 7.343l-.707.707zm-2.829-5.656a1 1 0 1 0-1.414 1.414l.707-.707zM6.597 7.83l-.372-.928zm6.99-2.143l.708-.707zm4.946 5.803l.929.372zm-.221-1.078l.707-.708zm-2.144 6.99l-.928-.37zm-.801.621l-.126-.992zm.801-.62l.929.371l2.365-5.912l-.929-.372l-.928-.371l-2.365 5.912zm2.144-6.991l.707-.708l-4.724-4.724l-.707.707l-.707.707l4.724 4.725zm-5.803-4.946l-.371-.929l-5.913 2.365l.372.929l.37.928l5.914-2.365zM3.93 20.07l.268.964l.002-.001l.008-.002l.034-.01l.131-.035a79 79 0 0 1 2.128-.549c1.308-.319 2.848-.66 3.913-.788l-.12-.993l-.12-.993c-1.195.145-2.838.512-4.147.831a90 90 0 0 0-2.179.562l-.137.037l-.036.01l-.01.003h-.002zm6.364-1.414l.12.993c1.644-.2 3.999-.497 5.08-.634l-.127-.992l-.125-.992c-1.081.137-3.43.434-5.068.632zM5.976 8.634l-.992-.126c-.137 1.08-.434 3.435-.634 5.079l.993.12l.993.12c.198-1.637.495-3.987.632-5.068zm-.633 5.073l-.993-.12c-.129 1.065-.47 2.605-.788 3.913a89 89 0 0 1-.584 2.26l-.01.033l-.002.008v.002l1.926.536v-.001l.001-.003l.003-.01l.01-.035a49 49 0 0 0 .172-.64a90 90 0 0 0 .427-1.676c.32-1.31.686-2.951.83-4.146zm-.707 5.657l.707.707L11 14.414l-.707-.707L9.586 13l-5.657 5.657zm5.657-7.07L11 13l.707-.707l.707-.707a2 2 0 0 0-2.828 0zm1.414 0L11 13l.707.707l.707.707a2 2 0 0 0 0-2.828zm0 1.413L11 13l-.707.707l-.707.707a2 2 0 0 0 2.828 0zm-1.414 0L11 13l-.707-.707l-.707-.707a2 2 0 0 0 0 2.829zm9.9-5.657l.707-.707l-4.243-4.242l-.707.707l-.707.707l4.243 4.242zM6.597 7.832l-.372-.929c-.674.27-1.15.884-1.24 1.605l.991.126l.992.125v.001zm6.99-2.144l.708-.707a2 2 0 0 0-2.157-.443l.371.929l.371.928zm4.946 5.803l.929.372a2 2 0 0 0-.443-2.158l-.707.708l-.707.707zm-2.365 5.913l-.928-.372l.127.992l.125.992a2 2 0 0 0 1.605-1.241z"
		/>
	</>,
);
export const Plus = icon(
	<>
		<path fill="none" stroke="currentColor" strokeLinecap="round" d="M5 12h14m-7 7V5" />
	</>,
);
export const Reply = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			strokeLinejoin="round"
			d="M9.5 13.5L5 9l4.5-4.5M5.5 9H16a2 2 0 0 1 2 2v7"
		/>
	</>,
);
export const Search = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			d="m15.879 15.879l4.242 4.242M18 10.5a7.5 7.5 0 1 1-15 0a7.5 7.5 0 0 1 15 0Z"
		/>
	</>,
);
export const Send = icon(
	<>
		<path fill="none" stroke="currentColor" strokeLinejoin="round" d="M20 5L8.5 14.5V18l2-2M3 9l17.5-4.5l-6 15.5z" />
	</>,
);
export const ShieldAlert = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			d="m8.464 15.536l7.072-7.071M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0Z"
		/>
	</>,
);
export const Star = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			d="M11.784 2.87a.25.25 0 0 1 .432 0l2.961 5.085a.25.25 0 0 0 .164.119l5.75 1.245a.25.25 0 0 1 .134.41l-3.92 4.388a.25.25 0 0 0-.063.192l.593 5.854a.25.25 0 0 1-.35.254l-5.384-2.373a.25.25 0 0 0-.202 0l-5.384 2.373a.25.25 0 0 1-.35-.254l.593-5.854a.25.25 0 0 0-.062-.192L2.776 9.73a.25.25 0 0 1 .133-.411l5.75-1.245a.25.25 0 0 0 .164-.119z"
		/>
	</>,
);
export const Trash2 = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			d="m5 6l.876 13.133A2 2 0 0 0 7.87 21h8.258a2 2 0 0 0 1.995-1.867L19 6M8 6l.772-2.316A1 1 0 0 1 9.721 3h4.558a1 1 0 0 1 .949.684L16 6m-6 5v5m4-5v5M4 6h16"
		/>
	</>,
);
export const Underline = icon(
	<>
		<path fill="none" stroke="currentColor" strokeLinecap="round" d="M6 20h12M7 4v7a5 5 0 0 0 10 0V4" />
	</>,
);
export const User = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			d="M20 18.5c0 1.933-3.582 2.5-8 2.5s-8-.567-8-2.5S7.582 14 12 14s8 2.567 8 4.5ZM16 7a4 4 0 1 1-8 0a4 4 0 0 1 8 0Z"
		/>
	</>,
);
export const X = icon(
	<>
		<path
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			d="m5.636 5.637l12.728 12.728m-12.728 0L18.364 5.637"
		/>
	</>,
);
