// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string
	AccountID             string
	ProviderID            string
	UserID                string
	AccessToken           pgtype.Text
	RefreshToken          pgtype.Text
	IDToken               pgtype.Text
	AccessTokenExpiresAt  pgtype.Timestamp
	RefreshTokenExpiresAt pgtype.Timestamp
	Scope                 pgtype.Text
	Password              pgtype.Text
	CreatedAt             pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
}

type ChangeLog struct {
	AccountID string
	Version   int64
	Entity    string
	EntityID  string
	Op        string
	CreatedAt pgtype.Timestamptz
}

type MailAccount struct {
	ID        string
	UserID    string
	Email     string
	ImapHost  string
	ImapPort  int32
	SmtpHost  string
	SmtpPort  int32
	Username  string
	Secret    []byte
	Version   int64
	CreatedAt pgtype.Timestamptz
}

type Mailbox struct {
	ID          string
	AccountID   string
	Name        string
	UidValidity int64
	Role        string
}

type Message struct {
	ID          string
	AccountID   string
	MailboxID   string
	Uid         int64
	MessageID   string
	Subject     string
	FromName    string
	FromAddr    string
	SentAt      pgtype.Timestamptz
	Flags       []string
	Size        int32
	Snippet     string
	Attachments []byte
}

type Passkey struct {
	ID           string
	Name         pgtype.Text
	PublicKey    string
	UserID       string
	CredentialID string
	Counter      int32
	DeviceType   string
	BackedUp     bool
	Transports   pgtype.Text
	CreatedAt    pgtype.Timestamp
	Aaguid       pgtype.Text
}

type Session struct {
	ID        string
	ExpiresAt pgtype.Timestamp
	Token     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	UserID    string
}

type TwoFactor struct {
	ID                      string
	Secret                  string
	BackupCodes             string
	UserID                  string
	Verified                pgtype.Bool
	FailedVerificationCount pgtype.Int4
	LockedUntil             pgtype.Timestamp
}

type User struct {
	ID               string
	Name             string
	Email            string
	EmailVerified    bool
	Image            pgtype.Text
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	TwoFactorEnabled pgtype.Bool
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
