// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const latestVersion = `-- name: LatestVersion :one
SELECT COALESCE(MAX(version), 0)::bigint FROM change_log WHERE account_id = $1
`

func (q *Queries) LatestVersion(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, latestVersion, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
