// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearMailbox = `-- name: ClearMailbox :many
DELETE FROM message WHERE mailbox_id = $1 RETURNING id
`

func (q *Queries) ClearMailbox(ctx context.Context, mailboxID string) ([]string, error) {
	rows, err := q.db.Query(ctx, clearMailbox, mailboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMailbox = `-- name: CreateMailbox :exec
INSERT INTO mailbox (id, account_id, name, role, uid_validity) VALUES ($1, $2, $3, $4, $5)
`

type CreateMailboxParams struct {
	ID          string
	AccountID   string
	Name        string
	Role        string
	UidValidity int64
}

func (q *Queries) CreateMailbox(ctx context.Context, arg CreateMailboxParams) error {
	_, err := q.db.Exec(ctx, createMailbox,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.Role,
		arg.UidValidity,
	)
	return err
}

const deleteMailbox = `-- name: DeleteMailbox :exec
DELETE FROM mailbox WHERE id = $1
`

func (q *Queries) DeleteMailbox(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMailbox, id)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM message WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, email, imap_host, imap_port, smtp_host, smtp_port, username, secret, version, created_at FROM mail_account WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (MailAccount, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i MailAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.ImapHost,
		&i.ImapPort,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.Username,
		&i.Secret,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const getMailbox = `-- name: GetMailbox :one
SELECT id, account_id, name, uid_validity, role FROM mailbox WHERE account_id = $1 AND name = $2
`

type GetMailboxParams struct {
	AccountID string
	Name      string
}

func (q *Queries) GetMailbox(ctx context.Context, arg GetMailboxParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, getMailbox, arg.AccountID, arg.Name)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.UidValidity,
		&i.Role,
	)
	return i, err
}

const getMessagePlace = `-- name: GetMessagePlace :one
SELECT m.uid, b.name FROM message m JOIN mailbox b ON b.id = m.mailbox_id WHERE m.id = $1 AND m.account_id = $2
`

type GetMessagePlaceParams struct {
	ID        string
	AccountID string
}

type GetMessagePlaceRow struct {
	Uid  int64
	Name string
}

func (q *Queries) GetMessagePlace(ctx context.Context, arg GetMessagePlaceParams) (GetMessagePlaceRow, error) {
	row := q.db.QueryRow(ctx, getMessagePlace, arg.ID, arg.AccountID)
	var i GetMessagePlaceRow
	err := row.Scan(&i.Uid, &i.Name)
	return i, err
}

const insertMessage = `-- name: InsertMessage :execrows
INSERT INTO message (id, account_id, mailbox_id, uid, message_id, subject, snippet, from_name, from_addr, sent_at, flags, size)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (mailbox_id, uid) DO NOTHING
`

type InsertMessageParams struct {
	ID        string
	AccountID string
	MailboxID string
	Uid       int64
	MessageID string
	Subject   string
	Snippet   string
	FromName  string
	FromAddr  string
	SentAt    pgtype.Timestamptz
	Flags     []string
	Size      int32
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMessage,
		arg.ID,
		arg.AccountID,
		arg.MailboxID,
		arg.Uid,
		arg.MessageID,
		arg.Subject,
		arg.Snippet,
		arg.FromName,
		arg.FromAddr,
		arg.SentAt,
		arg.Flags,
		arg.Size,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAccountIDs = `-- name: ListAccountIDs :many
SELECT id FROM mail_account
`

func (q *Queries) ListAccountIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlags = `-- name: ListFlags :many
SELECT id, uid, flags FROM message WHERE mailbox_id = $1
`

type ListFlagsRow struct {
	ID    string
	Uid   int64
	Flags []string
}

func (q *Queries) ListFlags(ctx context.Context, mailboxID string) ([]ListFlagsRow, error) {
	rows, err := q.db.Query(ctx, listFlags, mailboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlagsRow
	for rows.Next() {
		var i ListFlagsRow
		if err := rows.Scan(&i.ID, &i.Uid, &i.Flags); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailboxes = `-- name: ListMailboxes :many
SELECT id, account_id, name, uid_validity, role FROM mailbox WHERE account_id = $1
`

func (q *Queries) ListMailboxes(ctx context.Context, accountID string) ([]Mailbox, error) {
	rows, err := q.db.Query(ctx, listMailboxes, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mailbox
	for rows.Next() {
		var i Mailbox
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.UidValidity,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logChange = `-- name: LogChange :one
WITH v AS (UPDATE mail_account SET version = version + 1 WHERE id = $1 RETURNING version)
INSERT INTO change_log (account_id, version, entity, entity_id, op)
SELECT $1, v.version, $2, $3, $4 FROM v
RETURNING version
`

type LogChangeParams struct {
	AccountID string
	Entity    string
	EntityID  string
	Op        string
}

func (q *Queries) LogChange(ctx context.Context, arg LogChangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, logChange,
		arg.AccountID,
		arg.Entity,
		arg.EntityID,
		arg.Op,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const maxUID = `-- name: MaxUID :one
SELECT COALESCE(MAX(uid), 0)::bigint FROM message WHERE mailbox_id = $1
`

func (q *Queries) MaxUID(ctx context.Context, mailboxID string) (int64, error) {
	row := q.db.QueryRow(ctx, maxUID, mailboxID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setFlags = `-- name: SetFlags :exec
UPDATE message SET flags = $2 WHERE id = $1
`

type SetFlagsParams struct {
	ID    string
	Flags []string
}

func (q *Queries) SetFlags(ctx context.Context, arg SetFlagsParams) error {
	_, err := q.db.Exec(ctx, setFlags, arg.ID, arg.Flags)
	return err
}

const updateMailbox = `-- name: UpdateMailbox :exec
UPDATE mailbox SET role = $2, uid_validity = $3 WHERE id = $1
`

type UpdateMailboxParams struct {
	ID          string
	Role        string
	UidValidity int64
}

func (q *Queries) UpdateMailbox(ctx context.Context, arg UpdateMailboxParams) error {
	_, err := q.db.Exec(ctx, updateMailbox, arg.ID, arg.Role, arg.UidValidity)
	return err
}
